### PR TITLE
Make pip installable 

### PR DESCRIPTION
**Pull request by dentalfloss1**
This would address issue #21 . I took some guesses on the information in setup.py @jaycedowell  it would be helpful if you could edit that file to correct the description and version number.

### CODE REVIEW

**Comment by jaycedowell** [comment]
I did a little work on this to make it look more like https://github.com/lwa-project/pasi_image.  It's better but I'm still not 100% happy with it.  The things that are bothering me:
 1. `namespace_packages` is deprecated for setuptools.  It needs to be migrated over to [PEP 420](https://peps.python.org/pep-0420/)
 2. Including `bad_freq.txt` in with the module is a mess.  The current scheme works but it is ugly.  Fixing this probably involves moving `bad_freq.txt` somewhere into the module's directory structure.  Moving it would also require a change to `orville_imager.py` so that it defaults to using what's installed with in the module.

**Comment by jaycedowell** [comment]
That PR into the branch takes care of my two concerns.  For (2) I decided to go with a sym link to the `bad_freq.txt` file that will install with the `lsl_toolkits`.

**Review by jaycedowell — APPROVED** [review]

**Comment by jaycedowell** [comment]
@dentalfloss1 do the changes I've made to this still work for you?

**Comment by dentalfloss1** [comment]
Looks good to  me.

________________________________

**Pull request merged**
